In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.0245537 , 0.35344998, 0.86582018, 0.5771614 , 0.77792748])

In [24]:
np.random.rand(5,5)

array([[0.22415024, 0.02420082, 0.35201401, 0.81575412, 0.70718233],
       [0.1714194 , 0.8065963 , 0.10647846, 0.84933717, 0.15037164],
       [0.5909446 , 0.05459926, 0.91371397, 0.92181295, 0.23004927],
       [0.4156257 , 0.69662244, 0.42664399, 0.62534608, 0.50538826],
       [0.22415896, 0.98757837, 0.07610137, 0.48871703, 0.0256565 ]])

In [25]:
np.random.randn(2)

array([ 0.54499151, -1.60379591])

In [26]:
np.random.randn(4,4)

array([[ 0.2628004 ,  0.46394987,  0.00561179, -1.74513304],
       [ 2.17820498, -0.34631945, -1.32163066, -1.33597594],
       [-0.54869811,  1.13549865,  1.46356384, -0.11187407],
       [ 1.0497537 , -1.20828891,  0.05132033,  2.4226334 ]])

In [28]:
np.random.randint(1,100)

87

In [29]:
np.random.randint(1,100,10)

array([21, 30, 18, 91, 27, 32, 86, 96,  2, 19])

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr = np.random.randint(0,50,10)

In [38]:
ranarr

array([12, 25,  1, 38,  1, 36,  8, 36, 12, 36])

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ranarr

array([12, 25,  1, 38,  1, 36,  8, 36, 12, 36])

In [41]:
ranarr.max()

38

In [42]:
ranarr.min()

1

In [43]:
ranarr.argmax()

3

In [44]:
ranarr.argmin()

2

In [46]:
arr.shape

(25,)

In [47]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr = arr.reshape(5,5)

In [50]:
arr.shape

(5, 5)

In [51]:
arr.dtype

dtype('int32')

In [52]:
from numpy.random import randint

In [53]:
randint(2,10)

7